config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "flats#index"

  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  validates :first_name, :last_name, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name])
  end

end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new

  end

  def create
    @flat = Flat.new(flat_params)
    @flat.save
    redirect_to flats_path
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
    @flat = Flat.find(params[:id])
    @flat.update(flat_params)
    redirect_to flats_path
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy
    redirect_to flats_path, status: :see_other
  end
  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests, :url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<div class="container">

  <h1>Edit flat</h1>
  <%= simple_form_for (@flat) do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :price_per_night %>
    <%= f.input :number_of_guests %>
    <%= f.input :url %>
    <%= f.button :submit ,class:"btn btn-primary"%>
  <% end %>
</div>

app/views/flats/index.html.erb
<nav class="navbar">
  <div class="container-fluid bg-light">
    <div class="container d-flex justify-content-between">
      <%= link_to "Simple Airbnb", flats_path, class:"navbar-brand text-dark p-2" %>
    <div class="d-flex">
        <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="query">
          <button class="btn btn-outline-success me-2" type="submit">Search</button>
        </form>
        <% if user_signed_in? %>
        <%= link_to "Add Flat", new_flat_path, class:"btn btn-outline-success me-2" %>
          <%= link_to "Logout", destroy_user_session_path, data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class:"btn btn-outline-success" %>
        <% else %>
          <%= link_to "Login", new_user_session_path, class:"btn btn-outline-success" %>
        <% end %>
    </div>
    </div>
  </div>
</nav>
<div class="container">
  <h1 class="py-3">All our Flats (<%= @flats.count %>)</h1>
<div class="row gx-5 gy-3">
  <% @flats.each do |flat| %>
    <div class="col-4">
  <div class="border bg-light shadow-sm">
    <div>
      <img alt="Le Wagon" src="<%= flat.url %>">
    </div>
    <div class="p-3 mt-2">
      <h5><%= flat.name %></h5>
      <p><%= flat.address %></p>
      <div class='d-flex'>
        <p class="pe-3"><i class="fa-solid fa-person pe-2 fa-lg"></i><%= flat.number_of_guests %></p>
        <p><i class="fa-solid fa-dollar-sign pe-2 fa-lg"></i><%= flat.price_per_night %></p>
      </div>
    </div>
  </div>
  <div class="border p-3 shadow-sm mb-3">
    <%= link_to "More Info", flat_path(flat), class:"ps-2" %>
    <%= link_to "Edit", edit_flat_path(flat), class:"ps-2 text-warning" %>
    <%= link_to "Delete", flat_path(flat), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class:"ps-2 text-danger" %>
  </div>
</div>
  <% end %>
  </div>

</div>

app/views/flats/new.html.erb
<div class="container">

  <h1>Add a new flat</h1>
  <%= simple_form_for (@flat) do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :price_per_night %>
    <%= f.input :number_of_guests %>
    <%= f.button :submit ,class:"btn btn-primary"%>
  <% end %>
</div>

app/views/flats/show.html.erb
<nav class="navbar">
  <div class="container-fluid bg-light">
    <div class="container d-flex justify-content-between">
      <%= link_to "Simple Airbnb", flats_path, class:"navbar-brand text-dark p-2" %>
    <div>
        <%= link_to "Add Flat", new_flat_path, class:"btn btn-outline-primary" %>
        <%= link_to "Sign Out", destroy_user_session_path, data: {turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class:"btn btn-outline-primary" %>
    </div>
    </div>
  </div>
</nav>

<div class="container">
  <img alt="Le Wagon" src="<%= @flat.url %>" class="show_image">
</div>

<div class="container d-flex justify-content-evenly wrapper">
    <div class="left w-50">

      <div class="border p-3 my-4 bg-light shadow-sm">
        <h3><%= @flat.name %></h3>
        <p><%= @flat.address %></p>
      </div>

      <div class="border p-3 my-4 bg-light shadow-sm">
        <h3>A bit more about this flat...</h3>
        <p><%= @flat.description %></p>
      </div>

      <div class="border p-3 my-4 bg-light shadow-sm">
        <h3>Details</h3>
        <div class='d-flex'>
          <p class="pe-3"><i class="fa-solid fa-person pe-2"></i><%= @flat.number_of_guests %></p>
          <p><i class="fa-solid fa-dollar-sign pe-2"></i><%= @flat.price_per_night %></p>
        </div>
      </div>
         <%= link_to "Edit Flat", edit_flat_path(@flat), class:"btn btn-success px-2 me-2 mb-4" %>
         <%= link_to "Delete", flat_path(@flat), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class:"ps-2 mb-4 btn btn-danger" %>
    </div>

    <div class="right">
      <div class="border p-3 my-4 bg-light shadow-sm">
        <h4>Book this place!</h4>

        <div class="input-group mb-3">
          <span class="input-group-text" id="from">From:</span>
          <input type="date" class="form-control" aria-label="from" aria-describedby="from">
        </div>

        <div class="input-group mb-3">
          <span class="input-group-text" id="to">To:</span>
          <input type="date" class="form-control" aria-label="to" aria-describedby="to">
        </div>

        <button type="button" class="btn btn-success w-100">Book</button>

      </div>
      <div class="border pt-3 my-4 bg-light shadow-sm">
        <div class="d-flex justify-content-around">
          <h6>Share</h6>
          <p>
            <i class="fa-brands fa-square-facebook fa-lg"></i>
            <i class="fa-brands fa-square-twitter fa-lg"></i>
            <i class="fa-brands fa-square-instagram fa-lg"></i>
            <i class="fa-brands fa-square-twitter fa-lg"></i>
          </p>
        </div>

      </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render "shared/flashes" %>
  <%= yield %>
  </body>
</html>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>